; Hotkeys is From AutoHotkey v2 (Check Help inside AutoHotkey for more info)
; # = WIN
; ! = ALT
; ^ = CTRL
; + = SHIFT
; null = No hotkey assigned

; On Off Hotkeys for GUI (0 = disabled, 1 = enabled)
[GUI Hotkeys]
AlwaysOnTop=null
FkeyNumpad=null
Altarrow=null
SpacePan=null
Curslock=null

; F8 to toggle AlwaysOnTop mode
[AlwaysOnTop_config]
AlwaysOnTop_mode=F8 

; Toggle GUI (0 = disabled, 1 = enabled)
[Toggles]
Mod_AltArrow=0
Mod_AOT=0
Mod_SpacePan=0
Mod_FkeyNumpad=0
Mod_CursLock=1

[Settings]
FkeyNumpad_mode=NUMPAD

; GUI Settings for Curslock setting based your first monitor resolution
[Curslock_config]
Monitor1_W=1920
Monitor1_H=1080
Monitor2_Pos="DOWN"
GuiScale=1
GuiX_Offset=0
GuiY_Offset=0

[FkeyNumpad_config]
X=null
Y=950
